# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Linux build + AppImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dc: [ ldc-latest ]
        arch: [ x86_64 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Build
      run: |
        dub run :setup
        dub build --build=release
        cd appimage
        ./appimage-build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: appimage
        path: ./appimage/etichetta-x86_64.AppImage


